export {default as WhiteCloseIcon} from './close.svg'
export {default as WhitePlayIcon} from './play.svg'
export {default as BgIcon} from './bg.png'
export {default as CalendarIcon} from './calendar.svg'
export {default as RankIcon} from './rank.svg'
export {default as IMDBIcon} from './imdb.svg'
export {default as PlayIcon} from './play2.svg'